# Generated by Django 6.0.3 on 2026-03-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_user'),
        ('onboarding', '0003_alter_bankdetails_id_alter_idproof_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idproof',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_proof', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='laptopallocation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='laptopallocation',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_laptops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
