# Generated by Django 6.0.3 on 2026-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
