# Generated by Django 6.0.3 on 2026-03-17 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendence_check_in_time'),
        ('employees', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='employees.employee'),
        ),
    ]
